###GET
GET http://localhost:8081/teste/users

###POST
POST http://localhost:8081/teste/criar
Content-Type: application/json

{
    "nome" : " SVFSV",
    "cpf" : "46326463436",
    "endereco" : "casa",
    "email" : "andre.fop@upebr",
    "senha" : "andre rack"
}