###GET
GET http://localhost:8080/teste/users

###POST
POST http://localhost:8080/teste/criar
Content-Type: application/json

{
    "nome" : "AndrePereira",
    "cpf" : "300000",
    "endereco" : "Gravatá pernambuco",
    "email" : "sab@hotmail.com",
    "senha" : "casa123"

}